name: Issue Automations
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  on-new-issue:
    runs-on: ubuntu-latest
    steps:
      # 2A: Auto-comment
      - uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "👋 Thanks for opening this issue!"
            });

      # Auto-label bug (case-insensitive)
      - uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = (context.payload.issue.title || "").toLowerCase();
            const body  = (context.payload.issue.body  || "").toLowerCase();
            if (title.includes("bug") || body.includes("bug")) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ["bug"]
              });
            }

     
